from enum import Enum, auto


class TokenType(int, Enum):
    IDENTIFIER = auto()
    INTEGER = auto()
    FLOAT = auto()
    CHARACTER = auto()
    STRING = auto()
    NULL = auto()

    MUT = auto()

    RETURN = auto()
    NATIVE = auto()
    UNSAFE = auto()
    SAFE = auto()
    IF = auto()
    MATCH = auto()
    CASE = auto()
    DEFAULT = auto()
    ELSE = auto()
    DO = auto()
    WHILE = auto()
    LOOP = auto()
    BREAK = auto()
    CONTINUE = auto()
    IS = auto()
    AS = auto()
    IMPORT = auto()

    TRUE = auto()
    FALSE = auto()

    QUESTION = auto()
    EXCLAMATION = auto()

    LSHIFT = auto()
    RSHIFT = auto()
    OR = auto()
    AND = auto()
    XOR = auto()
    GE = auto()
    GT = auto()
    LE = auto()
    LT = auto()
    NE = auto()
    EQEQ = auto()
    EQ = auto()
    LBRACE = auto()
    RBRACE = auto()
    LPAREN = auto()
    RPAREN = auto()
    PLUS = auto()
    MINUS = auto()
    TIMES = auto()
    DIVIDE = auto()
    MOD = auto()
    TILDE = auto()
    POWER = auto()
    COLON = auto()
    COMMA = auto()
    DOT = auto()
    VARARGS = auto()

    EOF = auto()
